version: '3.3'

services:
  nextcloud-db:
    image: linuxserver/mariadb
    container_name: nextcloud-db
    restart: always
    volumes:
      - /var/docker/nextcloud/database_var:/var/lib/mysql
      - /var/docker/nextcloud/database_config:/config
    environment:
      - TZ=Europe/Berlin
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD= # Setze hier ein starkes Passwort
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=# Ein anderes Passwort
	  
	networks:
      - internal_nextcloud
	

  # nextcloud-db-backup:
  #   image: databack/mysql-backup
  #   container_name: nextcloud-db-backup
  #   depends_on:
  #     - nextcloud-db
  #   restart: always
  #   volumes:
  #     - /var/docker/nextcloud/backup:/db
  #   environment:
  #     - DB_DUMP_FREQ=60 # Backup jede Stunde - Angabe in Minuten
  #     - DB_DUMP_BEGIN=2300 # Backup startet immer um 23 Uhr
  #     - DB_DUMP_TARGET=/db
  #     - DB_SERVER=nextcloud-db
  #     - DB_USER=nextcloud
  #     - DB_PASS= # Starkes Passwort von MYSQL_PASSWORD
  #   user: "0" # Führt Backup als root User durch - ggf. anpassen
  #   networks:
  #     - internal_nextcloud


  nextcloud-app:
    image: nextcloud
    container_name: nextcloud-app
    restart: always
    volumes: 
      - /var/docker/nextcloud/app:/var/www/html
    links:
      - nextcloud-db
    networks:
      - internal_nextcloud
      - default

networks:
  internal_nextcloud:
	driver: bridge
    internal: true
  default:
    driver: bridge
