---
version: '3.3'

services: 
  nextcloud-db:
    image: mariadb
    container_name: nextcloud-db
    command: --transaction-isolation=READ-COMMITTED --log-bin=ROW
    networks:
        - nextcloud-db
    restart: always
    volumes:
      - /var/docker/nextcloud/database:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
        MYSQL_PASSWORD_FILE: /run/secrets/mysql_user_password
        MYSQL_DATABASE: nextcloud
        MYSQL_USER: nextcloud
        MYSQL_INITDB_SKIP_TZINFO: 1 # Behebt die bekannten Startprobleme der Datenbank
    secrets:
      - mysql_root_password
      - mysql_user_password
      
  nextcloud-redis:
    image: redis:alpine
    container_name: nextcloud-redis
    hostname: nextcloud-redis
    environment:
        REDIS_PASSWORD: XXXXXXX 
        # Redis Passwort wählen (Es gibt einen Workaround für Redis Secrets, aber wir sollten warten, bis das Ganze offiziell ist)
    networks:
        - default
    restart: always
    
  nextcloud-app:
    image: nextcloud
    container_name: nextcloud-app
    restart: always
    depends_on:
      - nextcloud-db
      - nextcloud-redis
    environment:
        MYSQL_USER: nextcloud
        MYSQL_DATABASE: nextcloud
        MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
        MYSQL_PASSWORD_FILE: /run/secrets/mysql_user_password
        REDIS_HOST: nextcloud-redis
        REDIS_HOST_PASSWORD= XXXXXXX # Redis Passwort wählen (gleiches, wie oben)
    secrets:
      - mysql_root_password
      - mysql_user_password
    volumes: 
      - /var/docker/nextcloud/app:/var/www/html
      # - EXTERNES DATENVERZEICHNIS:/var/www/html/data 
    links:
      - nextcloud-db
      - nextcloud-redis
    networks:
      - nextcloud-db
      - default
    
networks:
  nextcloud-db:
    driver: bridge
    internal: true
  default:
    driver: bridge
    
secrets:
  mysql_root_password:
    file: /opt/docker/secrets/mysql_root_password
  mysql_user_password:
    file: /opt/docker/secrets/mysql_user_password
