---
version: '3.3'

services: 
  nextcloud-db:
    image: mariadb
    container_name: nextcloud-db
    command: --transaction-isolation=READ-COMMITTED --log-bin=ROW
    networks:
        - nextcloud-db
    restart: always
    volumes:
      - /home/nextcloud/storage/database:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
        #MYSQL_PASSWORD_FILE: /run/secrets/mysql_user_password
        MYSQL_PASSWORD: test123
        MYSQL_DATABASE: nextcloud
        MYSQL_USER: nextcloud
        MYSQL_INITDB_SKIP_TZINFO: 1 # Behebt die bekannten Startprobleme der Datenbank
    secrets:
      - mysql_root_password
      - mysql_user_password
    
  nextcloud-app:
    image: nextcloud
    container_name: nextcloud-app
    restart: always
    depends_on:
      - nextcloud-db
    environment:
        MYSQL_HOST: nextcloud-db
        MYSQL_USER: nextcloud
        MYSQL_DATABASE: nextcloud
        #MYSQL_PASSWORD_FILE: /run/secrets/mysql_user_password
        MYSQL_PASSWORD: test123
    secrets:
      - mysql_root_password
      - mysql_user_password
    volumes: 
      - /home/nextcloud/storage/app:/var/www/html
      # - EXTERNES DATENVERZEICHNIS:/var/www/html/data 
    links:
      - nextcloud-db
    networks:
      - nextcloud-db
      - default
    ports:
      - 80:80
      - 443:443
    
networks:
  nextcloud-db:
    driver: bridge
    internal: true
  default:
    driver: bridge
    
secrets:
  mysql_root_password:
    file: /home/nextcloud/secrets/mysql_root_password
  mysql_user_password:
    file: /home/nextcloud/secrets/mysql_user_password
