---
version: '3.3'

services: 
  nextcloud-db:
    image: mariadb
    container_name: nextcloud-db
    command: --transaction-isolation=READ-COMMITTED --log-bin=ROW
    networks:
        - nextcloud-db
    restart: always
    volumes:
      - /var/docker/nextcloud/database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD= # Datenbank Passwort w채hlen
      - MYSQL_PASSWORD= # Datenbank Passwort w채hlen, wird bei der Nextcloudinstallation abgefragt
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_INITDB_SKIP_TZINFO=1 # Behebt die bekannten Startprobleme der Datenbank
      
  nextcloud-redis:
    image: redis:alpine
    container_name: nextcloud-redis
    hostname: nextcloud-redis
    environment:
        REDIS_PASSWORD: XXXXXXX # Redis Passwort w채hlen
    networks:
        - default
    restart: always
    
  nextcloud-app:
    image: nextcloud
    container_name: nextcloud-app
    restart: always
    depends_on:
      - nextcloud-db
      - nextcloud-redis
    environment:
        REDIS_HOST: nextcloud-redis
        REDIS_HOST_PASSWORD: XXXXXXX # Redis Passwort w채hlen (gleiches, wie oben)
    volumes: 
      - /var/docker/nextcloud/app:/var/www/html
      # - EXTERNES DATENVERZEICHNIS:/var/www/html/data 
    links:
      - nextcloud-db
    networks:
      - nextcloud-db
      - default
    
networks:
  nextcloud-db:
    driver: bridge
    internal: true
  default:
    driver: bridge
