---
version: '3.3'

services: 
  nextcloud-db:
    image: mariadb
    container_name: nextcloud-db
    command: --transaction-isolation=READ-COMMITTED --log-bin=ROW
    networks:
        - nextcloud-db
    restart: always
    volumes:
      - /var/docker/nextcloud/database:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
        MYSQL_PASSWORD_FILE: /run/secrets/mysql_user_password
        MYSQL_DATABASE: nextcloud
        MYSQL_USER: nextcloud
        MYSQL_INITDB_SKIP_TZINFO: 1 # Behebt die bekannten Startprobleme der Datenbank
    secrets:
      - mysql_root_password
      - mysql_user_password
    
  nextcloud-app:
    image: nextcloud
    container_name: nextcloud-app
    restart: always
    depends_on:
      - nextcloud-db
    environment:
        MYSQL_USER: nextcloud
        MYSQL_DATABASE: nextcloud
        MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
        MYSQL_PASSWORD_FILE: /run/secrets/mysql_user_password
    secrets:
      - mysql_root_password
      - mysql_user_password
    volumes: 
      - /var/docker/nextcloud/app:/var/www/html
      # - EXTERNES DATENVERZEICHNIS:/var/www/html/data 
    links:
      - nextcloud-db
    networks:
      - nextcloud-db
      - default
    
networks:
  nextcloud-db:
    driver: bridge
    internal: true
  default:
    driver: bridge
    
secrets:
  mysql_root_password:
    file: /opt/docker/secrets/mysql_root_password
  mysql_user_password:
    file: /opt/docker/secrets/mysql_user_password
